name: test_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

flutter_intl:
  enabled: true
  main_locale: en
  arb_dir: assets/l10n

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  #flutter pub run intl_utils:generate
  intl_utils: ^2.3.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  global_configuration: ^2.0.0-nullsafety.1
  flutter_simple_dependency_injection: ^2.0.0
  #flutter packages pub run build_runner build
  hive: ^2.0.6
  path_provider: ^2.0.8
  provider: ^6.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_launcher_icons: ^0.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0


flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/iconA.png"
  image_path_ios: "assets/icons/iconI.png"

flutter:

  uses-material-design: true

  assets:
   - assets/cfg/
   - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
